/**
 * New node file
 */

var PROTOCOL_RESTYPE_STATIC = 0;
var PROTOCOL_RESTYPE_FILE	= 1;
var PROTOCOL_RESTYPE_DYNAMIC = 30000;


var PROTOCOL_TRANSTYPE_ONESHOT = 0;
var PROTOCOL_TRANSTYPE_RETRYABLE = 1;
var PROTOCOL_TRANSTYPE_CUTANDPASTE = 2;

module.exports.PROTOCOL_RESTYPE_STATIC = PROTOCOL_RESTYPE_STATIC;
module.exports.PROTOCOL_RESTYPE_FILE = PROTOCOL_RESTYPE_FILE;
module.exports.PROTOCOL_RESTYPE_DYNAMIC = PROTOCOL_RESTYPE_DYNAMIC;

module.exports.PROTOCOL_TRANSTYPE_ONESHOT = PROTOCOL_TRANSTYPE_ONESHOT;
module.exports.PROTOCOL_TRANSTYPE_RETRYABLE = PROTOCOL_TRANSTYPE_RETRYABLE;
module.exports.PROTOCOL_TRANSTYPE_CUTANDPASTE = PROTOCOL_TRANSTYPE_CUTANDPASTE;

